### PR TITLE
fixed global nonce minimum

### PR DESCRIPTION
**Pull request by pigmej**

### CODE REVIEW

**Comment by fasmat** [comment]
The README as it is is correct. `NonceValue` in the second file (`0000488e171389cce69344d68b66f6b4`) is lower than the one in the first file (`0000ffda94993723a980bf557509773e`). Therefore the `Nonce` in the second file (`98765`) is the correct one to select 🙂.

**Comment by pigmej** [comment]
Then we have to make it more obvious:) but yeah I see now the logic there. Let me update :)

**Comment by poszu** [comment]
@nj what about this PR?

**Comment by nj** [comment]
> @nj what about this PR?

Most likely wrong tag - don't know of this project :wink:

**Comment by nj** [comment]
Hi @poszu

I assume you have tagged the wrong one - don't know of this project :wink:

**Comment by poszu** [comment]
> Hi @poszu
> 
> I assume you have tagged the wrong one - don't know of this project 😉

Sorry, I meant @pigmej who also uses "nj" in different places 😅.

**Review by poszu — APPROVED** [review]

**Pull request merged**
